In [404]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [405]:
df = pd.read_csv('tutorial.csv')
df

make  capacity   hp
0       BMW       4.0  300
1       BMW       4.0  315
2      AUDI       3.0  210
3  MERCEDES       6.3  450
4        VW       2.0  130

In [406]:
labelencoder = LabelEncoder()
ddf = pd.get_dummies(df.make)
ddf

AUDI  BMW  MERCEDES  VW
0     0    1         0   0
1     0    1         0   0
2     1    0         0   0
3     0    0         1   0
4     0    0         0   1

In [407]:
dummies = pd.get_dummies(df.make)
dummies

AUDI  BMW  MERCEDES  VW
0     0    1         0   0
1     0    1         0   0
2     1    0         0   0
3     0    0         1   0
4     0    0         0   1

In [408]:
merged = pd.concat([df, dummies], axis=1)
merged

make  capacity   hp  AUDI  BMW  MERCEDES  VW
0       BMW       4.0  300     0    1         0   0
1       BMW       4.0  315     0    1         0   0
2      AUDI       3.0  210     1    0         0   0
3  MERCEDES       6.3  450     0    0         1   0
4        VW       2.0  130     0    0         0   1

In [429]:
final = merged.drop(['make', 'VW'], axis='columns')
final

capacity   hp  AUDI  BMW  MERCEDES
0       4.0  300     0    1         0
1       4.0  315     0    1         0
2       3.0  210     1    0         0
3       6.3  450     0    0         1
4       2.0  130     0    0         0

In [430]:
model = LinearRegression()
X = final.drop('hp', axis=1)
X

capacity  AUDI  BMW  MERCEDES
0       4.0     0    1         0
1       4.0     0    1         0
2       3.0     1    0         0
3       6.3     0    0         1
4       2.0     0    0         0

In [431]:
y = final.hp
y

0    300
1    315
2    210
3    450
4    130
Name: hp, dtype: int64

In [432]:
model.fit(X.values, y.values)

LinearRegression()

In [433]:
model.predict(X.values)

array([307.5, 307.5, 210. , 450. , 130. ])

In [434]:
model.predict([[4.0, 0, 1, 0]])

array([307.5])

In [435]:
model.predict([[6.3, 0, 0, 1]])

array([450.])

In [475]:
model.score(X, y)

0.9954285526560606

# Label Encoder

In [503]:
le = LabelEncoder()
df

make  capacity   hp
0     1       4.0  300
1     1       4.0  315
2     0       3.0  210
3     2       6.3  450
4     3       2.0  130

In [513]:
dfle = df
dfle.make = le.fit_transform(dfle.make)
dfle

make  capacity   hp
0     1       4.0  300
1     1       4.0  315
2     0       3.0  210
3     2       6.3  450
4     3       2.0  130

In [514]:
X = dfle[['make', 'capacity']].values
X

array([[1. , 4. ],
       [1. , 4. ],
       [0. , 3. ],
       [2. , 6.3],
       [3. , 2. ]])

In [515]:
y = dfle.hp.values
y

array([300, 315, 210, 450, 130], dtype=int64)

In [516]:
# from sklearn.compose import ColumnTransformer

# ct = ColumnTransformer([('make', OneHotEncoder(), [0])], remainder = 'passthrough')

In [517]:
# X = ct.fit_transform(X)
# X

In [518]:
ohe = OneHotEncoder(handle_unknown='ignore')
X = ohe.fit_transform(X).toarray()
X

array([[0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0., 0., 0.]])

In [498]:
# X = X[:,1:]
# X

In [505]:
model.fit(X, y)

LinearRegression()

In [504]:
model.predict([[1., 0., 0., 0., 0., 1., 1., 0.]])

array([226.5625])

In [157]:
dfle = df.apply(LabelEncoder().fit_transform)
dfle

make  capacity  hp
0     1         2   2
1     1         2   3
2     0         1   1
3     2         3   4
4     3         0   0

In [158]:
oneh = OneHotEncoder(handle_unknown='ignore').fit(dfle)
oneh.categories_

[array([0, 1, 2, 3], dtype=int64),
 array([0, 1, 2, 3], dtype=int64),
 array([0, 1, 2, 3, 4], dtype=int64)]

In [159]:
oneh_t = oneh.transform(dfle).toarray()
oneh_t

array([[0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.]])